version: "2.3"

services:
  rpm:
    build:
      context: .
      args:
        - OS=${RPM_OS-fedora:37}
    volumes:
      - ..:/src:ro
      - ./RPMS:/root/rpmbuild/RPMS
      - ./SRPMS:/root/rpmbuild/SRPMS
